name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy whenever changes are pushed to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the workflow has permission to push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: Resume/resume  # Corrected path
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Configure Git User
        run: |
          git config --global user.email "thegrinch1985@gmail.com"
          git config --global user.name "github-actions"

      - name: Build Angular App
        working-directory: Resume/resume  # Ensure we are inside 'resume'
        run: ng build --configuration production --base-href /Resume/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Resume/resume/dist/resume  # Corrected path
          publish_branch: gh-pages
