name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy whenever changes are pushed to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular app
      - name: Configure Git User
        run: |
          git config --global user.email "thegrinch1985@gmail.com"
          git config --global user.name "github-actions"
      
        run: ng build --configuration production --base-href /Resume/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/resume  # Make sure this matches your output path in `angular.json`
