name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy whenever changes are pushed to 'main'

permissions:
  contents: write  # Ensure the workflow has permission to push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: resume  # Ensure correct directory
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Configure Git User
        run: |
          git config --global user.email "thegrinch1985@gmail.com"
          git config --global user.name "github-actions"

      - name: Build Angular App
        working-directory: resume  # Ensure we are in the correct directory
        run: ng build --configuration production --base-href /Resume/

      - name: Debug - Check if Build Folder Exists
        run: |
          ls -la resume/dist/resume  # Debugging step

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: resume/dist/resume  # Corrected path to dist folder
          force_orphan: true  # Ensure we fully replace previous deployment
